#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Findings persist to a local scratch file next to this script, not a repo
# .env — nothing here is a secret, and nothing here is meant to be committed.
# It's a record to paste into JDWLABS-285 and into the "Options" section of
# docs/lan-name-resolution.md once this wizard is done.
ENV_FILE="${ENV_FILE:-$(dirname "$0")/lan-dns-gateway-findings.env}"

# _first_ipv4 STRING — pull the first IPv4-looking token out of free-form
# human input. resolvectl/ipconfig output routinely carries the address
# buried in other text (interface names, a second address, IPv6 lines), and
# comparing that raw text against a bare "192.168.1.199" would silently fail
# even when the human answered correctly. Prints nothing on no match, which
# is deliberate: an empty string can never equal an address, so a bad paste
# fails onto the "not equal" branch below rather than an accidental partial
# match.
_first_ipv4() {
  grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' <<<"$1" | head -n1
}

banner "BGW320-500 — LAN DNS distribution check"

say "This checks whether the AT&T BGW320-500 gateway at 192.168.1.254 can hand"
say "out a custom DNS server to LAN clients via DHCP, and whether it actually"
say "honours that once set. Both are unconfirmed — docs/lan-name-resolution.md"
say "already established that the gateway has no per-name override page, which"
say "is a separate, already-answered question from the one this wizard checks."
note "Prerequisite: the resolver on 192.168.1.199 must already be live and"
note "verified (scenarios/lan-dns-resolver-deploy.md, Steps 1-3) before this"
note "wizard is useful — Stage 3 tests against it."

# ── Stage 1 — log in and find the DHCP subnet page ────────────────────────
stage "Gateway admin UI — log in"
say "The DNS-adjacent settings live under Home Network > Subnets & DHCP, or"
say "directly at the URL below once logged in."
open_url "http://192.168.1.254/cgi-bin/dhcpserver.ha"
step "Log in with the gateway's access code (physical device label, or the"
step "administrator account if one was set)."
step "If prompted for a login instead of landing on the DHCP page directly,"
step "navigate: Home Network > Subnets & DHCP > LAN subnet."
confirm "Did you reach the Subnets & DHCP page?" || {
  warn "Can't proceed without this page. Re-run the wizard once you're in."
  exit 1
}

# ── Stage 2 — look for a DNS server override field ─────────────────────────
stage "Look for a per-subnet DNS server field"
say "Look specifically for a DNS setting scoped to the LAN subnet's DHCP"
say "options (what clients are handed) — NOT the gateway's own WAN/Broadband"
say "DNS setting (what the gateway itself queries upstream). The two are"
say "easy to conflate and only one of them is relevant here."
note "If the field exists, it's usually a 'DNS Server' or 'Local DNS'"
note "entry under the LAN/subnet's DHCP configuration, sometimes with a"
note "Static/Dynamic toggle that has to be flipped to Static first."

# confirm() (library helper above) does the yes/no parsing — a hand-rolled
# `ask` + string-equality check here previously meant a human typing "y",
# "Yes", or anything but the literal string "yes" got silently routed to the
# "field doesn't exist" branch regardless of what they actually saw.
if confirm "Does such a field exist?"; then
  DHCP_DNS_FIELD_FOUND="yes"
else
  DHCP_DNS_FIELD_FOUND="no"
fi
write_env DHCP_DNS_FIELD_FOUND "$DHCP_DNS_FIELD_FOUND"

if [[ "$DHCP_DNS_FIELD_FOUND" == "no" ]]; then
  write_env DECISION "no-dhcp-override-field — gateway cannot advertise a custom DNS server; per-client static resolver config is the only distribution path"
  finish
  warn "No override field found. This is a real, useful finding — record it"
  warn "in docs/lan-name-resolution.md and JDWLABS-285: the resolver still"
  warn "works, but only for clients configured to use it by hand. Stop here;"
  warn "there is nothing further this wizard can check."
  exit 0
fi

step "Set the field to 192.168.1.199 (the resolver deployed by"
step "scenarios/lan-dns-resolver-deploy.md)."
step "If the page offers a second/secondary/fallback DNS field, set that one"
step "to 192.168.1.254 (the gateway's own address) too. Client failover"
step "between primary and secondary DNS is slow and not guaranteed, so this"
step "is a mitigation, not a fix — but a single resolver with no fallback"
step "means the whole LAN loses DNS the moment 192.168.1.199 is down for any"
step "reason, not just a DNS-specific one (see the 'If it goes down, all LAN"
step "clients lose all DNS' risk in docs/lan-name-resolution.md)."
step "Save."
confirm "Saved?" || { warn "Save it, then re-run this wizard from Stage 3."; exit 1; }

note "Rollback for this stage, if this ever needs undoing: return to this"
note "page, clear the DNS Server field back to its original value (blank, or"
note "'Automatic'/'Use gateway' if you didn't note the original setting"
note "before changing it — that's the safe default on this hardware), clear"
note "the secondary field the same way if you set one, then save. Clients"
note "keep using 192.168.1.199 until they renew their lease — force that the"
note "same way Stage 3 below does (release/renew, or toggle Wi-Fi off/on) if"
note "the rollback needs to take effect immediately rather than on next"
note "natural renewal."

# ── Stage 3 — force a client to pick up the new option and test it ────────
stage "Force a DHCP renewal and test what the client actually got"
say "The setting existing and saving is not proof a client uses it — that's"
say "the catch this stage exists to close."
step "On a LAN test client (not this machine if it's off-LAN), force a fresh"
step "DHCP lease: 'ipconfig /release && ipconfig /renew' (Windows),"
step "'sudo dhclient -r && sudo dhclient' (Linux), or toggle Wi-Fi off/on."
step "Check which DNS server the client was actually handed:"
step "  Windows: ipconfig /all | findstr /i \"DNS Servers\""
step "  Linux:   resolvectl status   (or: nmcli dev show | grep DNS)"
note "Paste the whole line if that's easier — only the address matters below,"
note "any surrounding text (interface name, a second address, etc.) is"
note "stripped automatically."
ask CLIENT_ASSIGNED_DNS "What DNS server address did the client report?:"
CLIENT_ASSIGNED_DNS="$(_first_ipv4 "$CLIENT_ASSIGNED_DNS")"
write_env CLIENT_ASSIGNED_DNS "$CLIENT_ASSIGNED_DNS"

say "Now query that exact address for cluster.jdwlabs.com from the same"
say "client — not 192.168.1.199 directly, and not the gateway directly."
step "nslookup cluster.jdwlabs.com   (uses the client's assigned resolver)"
ask CLIENT_LOOKUP_RESULT "What address did that return?:"
CLIENT_LOOKUP_RESULT="$(_first_ipv4 "$CLIENT_LOOKUP_RESULT")"
write_env CLIENT_LOOKUP_RESULT "$CLIENT_LOOKUP_RESULT"

if [[ "$CLIENT_ASSIGNED_DNS" != "192.168.1.199" ]]; then
  write_env DECISION "dhcp-option-not-honoured — field exists and saves, but clients are not actually handed 192.168.1.199; the gateway is not passing the option through"
  finish
  warn "The client wasn't handed 192.168.1.199 at all. The saved setting"
  warn "isn't reaching clients. Record this — it's the 'field exists but"
  warn "doesn't do what it says' failure mode, distinct from Stage 2's"
  warn "'field doesn't exist' failure mode, and both land on the same"
  warn "fallback (per-client static config)."
  exit 0
fi

if [[ "$CLIENT_LOOKUP_RESULT" != "192.168.1.199" ]]; then
  write_env DECISION "gateway-proxies-dns — client was handed 192.168.1.199 but still gets the public/WAN answer; the gateway is intercepting DNS traffic rather than letting the client reach the assigned resolver"
  finish
  warn "Client was assigned 192.168.1.199 but still got a different answer."
  warn "This is the gateway-proxying failure mode flagged in"
  warn "docs/lan-name-resolution.md — it's inserting itself in front of the"
  warn "assigned resolver rather than passing queries through. Confirmed,"
  warn "not hypothetical, on this hardware. Record it and fall back to"
  warn "per-client static resolver config."
  exit 0
fi

write_env DECISION "confirmed-working — DHCP hands out 192.168.1.199, gateway passes queries through untouched, client resolves cluster.jdwlabs.com to 192.168.1.199 with no per-client config"

# ── Stage 4 — record the result ────────────────────────────────────────────
stage "Record the result"
say "Both checks passed: the gateway advertises the resolver via DHCP and"
say "doesn't intercept queries to it. This is the automatic, travels-with-"
say "the-client outcome the ticket asked for."
note "Update docs/lan-name-resolution.md's 'Options, and the recommendation'"
note "section to record this as confirmed, and continue with"
note "scenarios/lan-dns-resolver-deploy.md Step 5 (DoD verification) from a"
note "second, previously-unconfigured LAN client."

finish
